name: Continuous Integration (Common)

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  save-pr:
    name: Save Pull Request Metadata
    runs-on: ubuntu-latest

    steps:
      - name: Build Artifact
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          MERGE_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $PR_SHA > ./pr/pr_sha
          echo $MERGE_SHA > ./pr/merge_sha

      - name: Upload Artifact
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: pr_number
          path: pr/

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Build)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: eips-wg/build
          path: build

      - name: Checkout (Content)
        uses: ./build/.github/actions/checkout-eips

      - name: Get Changed Files
        id: changed
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | sed -e 's|$|,|' | xargs -i echo "{}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@406322ec52dd7b488e48c1c4b82e2a8b3a1bf630
        with:
          check_filenames: true
          ignore_words_file: config/codespell-whitelist
          path: ${{ env.CHANGED_FILES }}
          skip: .git,**/*.png,**/*.gif,**/*.jpg,**/*.svg

  eipw-validator:
    name: EIP Validator (eipw)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (Build)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: eips-wg/build
          path: build

      - name: Checkout (Content)
        uses: ./build/.github/actions/checkout-eips

      - uses: ethereum/eipw-action@6785fa283773db4819cb0abf17a185a1d9b6eb9f
        name: Validate
        id: eipw-global
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unchecked: 1, 5069, 5757
          options-file: build/config/eipw.toml
          path: content/

  markdownlint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (Build)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: eips-wg/build
          path: build

      - name: Checkout (Content)
        uses: ./build/.github/actions/checkout-eips

      - name: Get Changed Files
        id: changed
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | grep -E -x '.*\.md' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@db43aef879112c3119a410d69f66701e0d530809
        with:
          config: config/markdownlint.yaml
          globs: |
            ${{ env.CHANGED_FILES }}
