name: Continuous Integration (Common)

on:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  save-pr:
    name: Save PR Number
    runs-on: ubuntu-latest

    steps:
      - name: Save PR number
        env:
          PR_NUMBER: ${{ github.event.number }}
          PR_SHA: ${{ github.event.pull_request.head.sha }}
          MERGE_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./pr
          echo $PR_NUMBER > ./pr/pr_number
          echo $PR_SHA > ./pr/pr_sha
          echo $MERGE_SHA > ./pr/merge_sha

      - name: Upload PR Number
        uses: actions/upload-artifact@65d862660abb392b8c4a3d1195a2108db131dd05
        with:
          name: pr_number
          path: pr/

  link-check:
    name: Link Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Link Checker
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec
        with:
          config-file: config/mlc_config.json
          use-quiet-mode: no
          use-verbose-mode: yes
          check-modified-files-only: yes

  codespell:
    name: CodeSpell
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Get Changed Files
        id: changed
        continue-on-error: true
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | sed -e 's|$|,|' | xargs -i echo "{}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run CodeSpell
        uses: codespell-project/actions-codespell@57beb9f38f49d773d641ac555d1565c3b6a59938
        if: steps.changed.outcome == 'success'
        with:
          check_filenames: true
          ignore_words_file: config/.codespell-whitelist
          path: ${{ env.CHANGED_FILES }}
          skip: .git,Gemfile.lock,**/*.png,**/*.gif,**/*.jpg,**/*.svg,.codespell-whitelist,vendor,_site,_config.yml,style.css

  eipw-validator:
    name: EIP Validator (eipw)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Checkout Build Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f
        with:
          repository: eips-wg/build
          path: build

      - uses: ethereum/eipw-action@6785fa283773db4819cb0abf17a185a1d9b6eb9f
        name: Validate (Global)
        id: eipw-global
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unchecked: 1, 5069, 5757
          options-file: build/config/eipw.toml
          path: content/

      - if: always()
        uses: ethereum/eipw-action@6785fa283773db4819cb0abf17a185a1d9b6eb9f
        name: Validate (WG)
        id: eipw-wg
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          unchecked: 1, 5069, 5757
          options-file: .wg/eipw.toml
          path: content/

  markdownlint:
    name: Markdown Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EIP Repository
        uses: actions/checkout@47fbe2df0ad0e27efb67a70beac3555f192b062f

      - name: Get Changed Files
        id: changed
        continue-on-error: true
        run: |
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          gh pr diff ${{ github.event.number }} --name-only | grep -E -x '[^/]+\.md|EIPS/eip-[0-9]+\.md' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint
        uses: DavidAnson/markdownlint-cli2-action@f5cf187ef11bd3a68a127321b794aa252ff23019
        if: steps.changed.outcome == 'success'
        with:
          command: config
          globs: |
            config/.markdownlint.yaml
            ${{ env.CHANGED_FILES }}
