name: Publish (Common)

on:
  workflow_call:

jobs:
  build:
    name: Build Pages
    runs-on: ubuntu-latest
    permissions:
      pages: read
    steps:
      - name: Fetch Pages Configuration
        id: get_pages
        uses: octokit/request-action@89697eb6635e52c6e1e5559f15b5c91ba5100cb0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          route: GET /repos/{owner}/{repo}/pages
          owner: ${{ github.event.repository.owner.login }}
          repo: ${{ github.event.repository.name }}

      - name: Checkout (Build)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
        with:
          repository: eips-wg/build
          path: build

      - name: Checkout (Content)
        uses: ./build/.github/actions/checkout-eips
        with:
          path: work

      - name: Render
        uses: ./build/.github/actions/render-eips
        with:
          base-url: "${{ fromJSON(steps.get_pages.outputs.data).html_url }}"
          root: work
          config: ./build/config/zola.toml

      - name: Upload Artifact
        id: artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa
        with:
          path: work/_site

  publish:
    name: Publish Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e
