name: Review (Common)

on:
  workflow_call:

jobs:
  review:
    runs-on: ubuntu-latest
    name: Review
    steps:
      - name: Fetch PR Number
        uses: dawidd6/action-download-artifact@246dbf436b23d7c49e21a7ab8204ca9ecd1fe615
        with:
          name: pr-number
          workflow: review-trigger.yml
          run_id: ${{ github.event.workflow_run.id }}

      - name: Save PR Number
        id: save-pr-number
        run: echo "pr=$(cat pr-number.txt)" >> $GITHUB_OUTPUT

      - name: Auto Review Bot
        id: auto-review-bot
        uses: ethereum/eip-review-bot@eips-wg-dist
        continue-on-error: true
        with:
          token: ${{ secrets.TOKEN }}
          pr_number: ${{ steps.save-pr-number.outputs.pr }}
